### ISSUE TITLE
WinAscent value

### ISSUE THREAD

**Issue by RosaWagner** [dy/wavefont#55]
Fontbakery is reporting some eventual clipping:

🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1270, but got 1200 instead [code: ascent]

@dy do you see any concern in raising the winAscent value?

**Comment by dy** [comment]
Let me see.

**Comment by dy** [comment]
I don't see that failure in [fontbakery report](https://dy.github.io/wavefont/out/fontbakery/fontbakery-report).
But it comes from "overflow" characters with values above 100.
In other words - 0-9 characters, as well as a-Z characters map to 0..100 values (main range), therefore ascent/descent are set as -200..1200 to meet line-height=1.4.
But extended latin range maps to 0..127 (with 27 values of overflow, useful for 0..127 programmatic values, like MIDI range or int type). If we increase ascent to match 0..127 range instead of 0..100, minimal line-height will become 1.54, which is too big for displaying waveform from 0..100 range.

Is that very critical to increase that value?

**Comment by dy** [comment]
To illustrate, ascent=1200 (lh=1.4):
<img width="620" alt="image" src="https://user-images.githubusercontent.com/300067/226982953-88739d6e-cc82-4db5-9888-bab2d3998f22.png">
with ascent=1270 (lh=1.54):
<img width="623" alt="image" src="https://user-images.githubusercontent.com/300067/226982856-1f9f6bad-3766-4de6-8d3b-d33b93c254b0.png">

If we take wavefont with ascent 1270 (min lh=1.54) and reduce line-height via CSS to 1.4, it creates selection overlap:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/300067/226984180-4cd0e4f0-b7c7-45b6-93e6-bef3053a8766.png">

Bigger ascent makes wavefont less responsive/usable.

**Comment by RosaWagner** [comment]
I may have a more recent version of Fontbakery.
Are you talking of the ascent value from typo/hhea, or win? Cause you can keep typo/hheaAscen to 1200, and have winAscent at 1270 to avoid clipping.

Otherwise it's okay to make an exception for this project I think

**Comment by dy** [comment]
It may have same issue for windows machines I'm afraid. Would be nice to make an exception for this particular case, it's sensitive parameter here.

**Comment by chrissimpkins** [comment]
OK to use designer defined Win metrics in this project.  Discussed with Rosalie today.
